version: '3'
name: 'nc-dev'

services:

  nextcloud:
    image: ghcr.io/juliushaertl/nextcloud-dev-php80:latest
    environment:
      SERVER_BRANCH: v27.1.5
    volumes:
      - ./data/shared:/shared
      - ./data/apps-extra/hmr_enabler:/var/www/html/apps-extra/hmr_enabler
      - ../:/var/www/html/apps-extra/templateapp
    ports:
      - "8080:80"
    extra_hosts:
      - host.docker.internal:host-gateway
